<section class="social-feed">
	<div id="social-feed-carousel" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner" role="listbox">
			<!--
			<div class="item active">
				<?php echo do_shortcode('[wp_rss_multi_importer category="1" showgroup="1"]'); ?>
			</div>
			-->
			<div class="item active">
				<?php echo do_shortcode('[wp_rss_multi_importer category="2" showgroup="1"]'); ?>
			</div>
			<div class="item">
			<?php echo do_shortcode('[wp_rss_multi_importer category="3" showgroup="1"]'); ?>
			</div>
		</div>
	</div>
</section>